# Generated by Django 5.1 on 2024-09-11 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=25)),
                ('address', models.TextField()),
                ('pimage', models.ImageField(upload_to='image')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
